/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ssi.holiday.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Holiday service. Represents a row in the &quot;ssi_holiday&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ssi.holiday.service.model.impl.HolidayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ssi.holiday.service.model.impl.HolidayImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Holiday
 * @see com.ssi.holiday.service.model.impl.HolidayImpl
 * @see com.ssi.holiday.service.model.impl.HolidayModelImpl
 * @generated
 */
@ProviderType
public interface HolidayModel extends BaseModel<Holiday> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a holiday model instance should use the {@link Holiday} interface instead.
	 */

	/**
	 * Returns the primary key of this holiday.
	 *
	 * @return the primary key of this holiday
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this holiday.
	 *
	 * @param primaryKey the primary key of this holiday
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the holiday ID of this holiday.
	 *
	 * @return the holiday ID of this holiday
	 */
	public int getHolidayId();

	/**
	 * Sets the holiday ID of this holiday.
	 *
	 * @param holidayId the holiday ID of this holiday
	 */
	public void setHolidayId(int holidayId);

	/**
	 * Returns the holiday name of this holiday.
	 *
	 * @return the holiday name of this holiday
	 */
	@AutoEscape
	public String getHolidayName();

	/**
	 * Sets the holiday name of this holiday.
	 *
	 * @param holidayName the holiday name of this holiday
	 */
	public void setHolidayName(String holidayName);

	/**
	 * Returns the holiday date of this holiday.
	 *
	 * @return the holiday date of this holiday
	 */
	public Date getHolidayDate();

	/**
	 * Sets the holiday date of this holiday.
	 *
	 * @param holidayDate the holiday date of this holiday
	 */
	public void setHolidayDate(Date holidayDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Holiday holiday);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Holiday> toCacheModel();

	@Override
	public Holiday toEscapedModel();

	@Override
	public Holiday toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}